version: '3.8'
services:
  task_manager:
    image: task_manager
    container_name: task_manager
    ports: 
      - 8070:8070
    expose:
      - 8070
    volumes:
      - ./envs/task_manager_env:/StorageUp/task_manager/.env

   
    
    
