version: '3.8'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    expose: 
     - 6379
    ports: 
     - 6379:6379
  upstorage_backend:
    image: ups_backend:latest
    container_name: ups_backend
    restart: always
    ports: 
      - 8080:8080
    volumes:
      - ./.env:/upstorage/backend/.env
    environment:
      DATABASE_CONNECTION: mongodb://host.docker.internal:27021/development
      #true - if MongoDB is replicas
      DATABASE_TRANSACTIONS: true
      REDIS_HOST: redis
      REDIS_PORT: 6379
    #For connect to MongoDB on host
    extra_hosts:
      - host.docker.internal:host-gateway
   
    
    
